apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  # DB_USER: superman@google.com
  # echo -n superman@google.com | base64
  PG_USER_EMAIL: c3VwZXJtYW5AZ29vZ2xlLmNvbQ==
  # DB_PASSWORD: EsSecretoElPass
  DB_PASSWORD: RXNTZWNyZXRvRWxQYXNz
