version: '3.7'

services:
    db:
      container_name: ${MONGO_DB_NAME}
      image: mongo:6.0
      volumes:
        - poke_vol:/data/db
      # ports:
      #   - 27017:27017
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      command: ['--auth'] # enable authentication cuando la imagen se levanata (ejecuta un o varios comandos)

    mongo-express:
      depends_on:
        - db
      image: mongo-express:1.0.0-alpha.4
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
        ME_CONFIG_MONGODB_SERVER: ${MONGO_DB_NAME}
      ports:
        - 8080:8081
      restart: always

    poke-app:
      depends_on:
        - db
        - mongo-express
      image: klerith/pokemon-nest-app:1.0.0
      ports:
        - 3000:3000
      environment:
        MONGODB: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_DB_NAME}:27017
        DB_NAME: ${MONGO_DB_NAME}
      restart: always


volumes:
  poke_vol:
    external: false